# Generated by Django 5.1.4 on 2025-01-01 22:15

import file_storing_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storing_app', '0002_remove_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[file_storing_app.validators.validate_file_type]),
        ),
    ]
