# Generated by Django 5.1.4 on 2025-01-02 12:27

import django.core.validators
import file_storing_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storing_app', '0003_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(validators=[file_storing_app.validators.validate_birth_date], verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{8}$', 'Invalid number.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
