# Generated by Django 5.1.4 on 2025-01-02 16:08

import file_storing_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storing_app', '0005_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(validators=[file_storing_app.validators.validate_birth_date], verbose_name='Birth Date'),
        ),
    ]
