# Generated by Django 5.1.4 on 2025-01-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storing_app', '0006_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
