# Generated by Django 5.1.4 on 2025-01-04 16:17

import file_storing_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storing_app', '0008_remove_customuser_username_document_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[file_storing_app.validators.validate_file_type, file_storing_app.validators.validate_file_size]),
        ),
    ]
